[package]
name = "zfs-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
regex = "1"
itertools = "0.10"
thiserror = "1"
anyhow = "1"
clap = "4"
rand = "0.8"
indicatif = "0.17"